### ISSUE TITLE
Dark theme doesn't apply

### ISSUE THREAD

**Issue by puddlewitt** [sapristi/mopidy-mowecl#4]
Maybe I'm missing something, but the dark theme doesn't appear to apply...

![image](https://user-images.githubusercontent.com/2998294/95000676-d1fce580-05ba-11eb-8b2b-78b6c88ed7b1.png)

**Comment by sapristi** [comment]
Yes maybe the name `Theme type` isn't very descriptive, but that's why there also is the `?` with some documentation (on the right) ! In short, this setting changes the button outline color (and maybe some other settings of material-ui) to adapt with dark themes.

To apply a dark theme, you have to individually set the three colors settings (and eventually set `Theme type` to dark if you want).
